"""Build an override config directory, invoke ActivitySim as a subprocess, capture everything.

Design (PLAN.md, Phase 1): every run lives in ``runs/<run_id>/`` with

- ``overrides/configs/settings.yaml``  ``inherit_settings: True`` + only the
  keys overridden for this run, plus any shadowing files (``--override-file``)
- ``output/``                           ActivitySim's output directory
- ``manifest.json``, ``stdout.log``, ``stderr.log``

ActivitySim's ``-c`` flag takes several config directories and the first one
listed wins, so the command is
``python -m activitysim run -c <overrides> -c example/configs -o <output> -d example/data``.
"""

from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Iterable

import yaml

from . import __version__, example, ledger, paths
from . import manifest as mf
from .jsonio import read_json_if_exists

LAST_CHECKPOINT = "_"  # ActivitySim's "resume after the last checkpoint" marker
ENV_PREFIXES = ("ASIM_", "ACTIVITYSIM", "OMP_", "MKL_", "NUMBA_", "OPENBLAS_", "PYTHON")


class HarnessError(Exception):
    """A user-facing error: bad arguments or missing prerequisites. Message is the explanation."""


def new_run_id(now: datetime | None = None) -> str:
    now = now or datetime.now(timezone.utc)
    return f"{now:%Y%m%d-%H%M%S}-{secrets.token_hex(3)}"


def parse_models(models: str | Iterable[str] | None) -> list[str] | None:
    if models is None:
        return None
    if isinstance(models, str):
        items = models.split(",")
    else:
        items = list(models)
    cleaned = [m.strip() for m in items if m and m.strip()]
    return cleaned or None


def build_settings_overrides(
    sample_size: int | None = None,
    resume_after: str | None = None,
    trace_hh_id: int | None = None,
    models: Iterable[str] | None = None,
    extra: dict | None = None,
) -> dict:
    """The dict written to overrides/configs/settings.yaml. Only overridden keys appear."""
    ov: dict = {"inherit_settings": True}
    if sample_size is not None:
        ov["households_sample_size"] = int(sample_size)
    if resume_after:
        ov["resume_after"] = str(resume_after)
    if trace_hh_id is not None:
        ov["trace_hh_id"] = int(trace_hh_id)
    if models:
        ov["models"] = list(models)
    if extra:
        ov.update(extra)
    return ov


def write_override_dir(
    run_dir: Path, settings_overrides: dict, override_files: Iterable[Path] | None = None
) -> tuple[Path, list[str]]:
    """Create runs/<id>/overrides/configs with settings.yaml and any shadowing files."""
    cfg = Path(run_dir) / "overrides" / "configs"
    cfg.mkdir(parents=True, exist_ok=True)
    with open(cfg / "settings.yaml", "w") as f:
        yaml.safe_dump(settings_overrides, f, sort_keys=False)
    names: list[str] = []
    for src in override_files or []:
        src = Path(src)
        if not src.is_file():
            raise HarnessError(f"override file not found: {src}")
        if src.name == "settings.yaml":
            raise HarnessError("settings.yaml is generated by the harness; pass settings as options")
        shutil.copy2(src, cfg / src.name)
        names.append(src.name)
    return cfg, names


def build_command(override_cfg: Path, output_dir: Path) -> list[str]:
    return [
        sys.executable, "-m", "activitysim", "run",
        "-c", str(override_cfg),
        "-c", str(paths.configs_dir()),
        "-o", str(output_dir),
        "-d", str(paths.data_dir()),
    ]


def _recorded_env() -> dict:
    env = {k: v for k, v in os.environ.items() if k.startswith(ENV_PREFIXES)}
    return {"python_executable": sys.executable, "variables": dict(sorted(env.items()))}


def parent_checkpoints(parent_output: Path) -> list[str]:
    """Checkpoint names stored in a run's parquet pipeline (in order)."""
    import pandas as pd  # local: pandas import is slow and only needed here

    cp = parent_output / paths.PIPELINE_DIRNAME / paths.CHECKPOINTS_FILENAME
    if not cp.is_file():
        return []
    df = pd.read_parquet(cp)
    col = "checkpoint_name" if "checkpoint_name" in df.columns else df.columns[0]
    return [str(x) for x in df[col].tolist()]


def run(
    label: str,
    *,
    sample_size: int | None = None,
    resume_from: str | None = None,
    resume_after: str | None = None,
    models: str | Iterable[str] | None = None,
    trace_hh_id: int | None = None,
    override_files: Iterable[Path] | None = None,
    extra_settings: dict | None = None,
    run_id: str | None = None,
    on_start: Callable[[dict], None] | None = None,
) -> dict:
    """Execute one ActivitySim run synchronously and return its final manifest.

    A model failure is a normal outcome: the manifest comes back with
    ``status == "failed"`` and the caller decides what to do. Only argument
    and prerequisite problems raise ``HarnessError``.
    """
    label = (label or "").strip()
    if not label:
        raise HarnessError("a --label describing the run is required")
    try:
        example.check_example()
    except example.ExampleMissing as e:
        raise HarnessError(str(e)) from e
    if resume_after and not resume_from:
        raise HarnessError("--resume-after needs --resume-from <run_id> (the run whose pipeline to reuse)")
    if resume_from and not resume_after:
        raise HarnessError(
            "--resume-from needs --resume-after <step>: the last step to keep from the parent run "
            f"(or {LAST_CHECKPOINT!r} for its last checkpoint)"
        )
    models = parse_models(models)
    if sample_size is not None and sample_size < 0:
        raise HarnessError("--sample-size must be >= 0 (0 means all households)")

    parent_id = parent = None
    parent_pipeline = None
    if resume_from:
        try:
            parent_id = ledger.resolve_run_id(resume_from)
        except KeyError as e:
            raise HarnessError(str(e)) from e
        parent_dir = paths.run_dir(parent_id)
        parent = mf.read_manifest(parent_dir)
        parent_pipeline = parent_dir / "output" / paths.PIPELINE_DIRNAME
        if not parent_pipeline.is_dir():
            raise HarnessError(f"run {parent_id} has no pipeline at {parent_pipeline}; cannot resume from it")
        if resume_after != LAST_CHECKPOINT:
            checkpoints = parent_checkpoints(parent_dir / "output")
            if checkpoints and resume_after not in checkpoints:
                raise HarnessError(
                    f"run {parent_id} has no checkpoint named {resume_after!r}; "
                    f"available: {', '.join(checkpoints)}"
                )
        if sample_size is None:
            sample_size = parent.get("sample_size")

    run_id = run_id or new_run_id()
    run_dir = paths.run_dir(run_id)
    if run_dir.exists():
        raise HarnessError(f"run directory already exists: {run_dir}")
    output_dir = run_dir / "output"
    output_dir.mkdir(parents=True)
    for sub in paths.OUTPUT_SUBDIRS:  # ActivitySim only uses log/ and trace/ if they exist
        (output_dir / sub).mkdir()
    if parent_pipeline is not None:
        shutil.copytree(parent_pipeline, output_dir / paths.PIPELINE_DIRNAME)

    settings_overrides = build_settings_overrides(
        sample_size=sample_size, resume_after=resume_after, trace_hh_id=trace_hh_id,
        models=models, extra=extra_settings,
    )
    override_cfg, override_names = write_override_dir(run_dir, settings_overrides, override_files)
    command = build_command(override_cfg, output_dir)

    manifest = {
        "run_id": run_id,
        "label": label,
        "created_at": mf.now_iso(),
        "finished_at": None,
        "duration_s": None,
        "status": "running",
        "exit_code": None,
        "command": command,
        "cwd": str(run_dir),
        "python_version": mf.python_version(),
        "activitysim_version": mf.activitysim_version(),
        "harness_version": __version__,
        "harness_git_sha": mf.harness_git_sha(paths.root()),
        "sample_size": sample_size,
        "models": models,
        "settings_overrides": settings_overrides,
        "override_files": override_names,
        "config_hash": mf.config_hash([override_cfg, paths.configs_dir()]),
        "data_fingerprint": mf.data_fingerprint(paths.data_dir()),
        "step_timings": {},
        "parent_run_id": parent_id,
        "example_dir": str(paths.example_dir()),
        "env": _recorded_env(),
    }
    mf.write_manifest(run_dir, manifest)
    ledger.append(ledger.row_from_manifest(manifest))
    if on_start:
        on_start(manifest)

    env = os.environ.copy()
    env.setdefault("PYTHONUNBUFFERED", "1")
    t0 = time.monotonic()
    try:
        with open(run_dir / "stdout.log", "wb") as out, open(run_dir / "stderr.log", "wb") as err:
            proc = subprocess.run(command, cwd=run_dir, env=env, stdout=out, stderr=err)
        exit_code = proc.returncode
    except KeyboardInterrupt:
        manifest.update(
            finished_at=mf.now_iso(), duration_s=round(time.monotonic() - t0, 1),
            status="failed", exit_code=None, note="interrupted",
            step_timings=mf.parse_step_timings(paths.find_timing_log(output_dir)),
        )
        mf.write_manifest(run_dir, manifest)
        ledger.upsert(ledger.row_for_run_dir(run_dir))
        raise

    manifest.update(
        finished_at=mf.now_iso(),
        duration_s=round(time.monotonic() - t0, 1),
        exit_code=exit_code,
        status="succeeded" if exit_code == 0 else "failed",
        step_timings=mf.parse_step_timings(paths.find_timing_log(output_dir)),
    )
    mf.write_manifest(run_dir, manifest)
    finalize(run_dir, manifest)
    ledger.upsert(ledger.row_for_run_dir(run_dir))
    return manifest


def finalize(run_dir: Path, manifest: dict) -> None:
    """Post-run artifacts: summary + scorecard on success, error.json on failure.

    Later phases fill this in; each hook is optional and must never raise.
    """
    hooks = _finalize_hooks()
    for hook in hooks:
        try:
            hook(run_dir, manifest)
        except Exception as e:  # noqa: BLE001 - a bad summary must not lose the run record
            notes = manifest.setdefault("finalize_errors", [])
            notes.append(f"{hook.__module__}.{hook.__name__}: {type(e).__name__}: {e}")
            mf.write_manifest(run_dir, manifest)


def _finalize_hooks() -> list[Callable[[Path, dict], None]]:
    hooks: list[Callable[[Path, dict], None]] = []
    try:
        from .summarize import finalize_hook as summarize_hook  # Phase 2
        hooks.append(summarize_hook)
    except ImportError:
        pass
    try:
        from .targets import finalize_hook as targets_hook  # Phase 2
        hooks.append(targets_hook)
    except ImportError:
        pass
    try:
        from .errors import finalize_hook as errors_hook  # Phase 3
        hooks.append(errors_hook)
    except ImportError:
        pass
    return hooks


def failure_explanation(run_dir: Path, manifest: dict) -> str:
    """One paragraph saying what failed, for stderr and for tool results."""
    run_dir = Path(run_dir)
    error = read_json_if_exists(run_dir / "error.json")
    if error:
        step = error.get("failed_step") or "an unknown step"
        exc = error.get("exception_type") or "Error"
        msg = (error.get("message") or "").strip().splitlines()
        first = msg[0] if msg else ""
        where = ""
        ctx = error.get("expression_context") or {}
        if ctx.get("spec_file"):
            where = f" while evaluating {ctx['spec_file']}"
            if ctx.get("expression"):
                where += f" expression {ctx['expression']!r}"
        return (
            f"Run {manifest.get('run_id')} ({manifest.get('label')!r}) failed in step {step}{where}: "
            f"{exc}: {first}. Exit code {manifest.get('exit_code')}. "
            f"Details: {run_dir / 'error.json'}; full log: {error.get('log_path') or paths.find_log_file(run_dir / 'output')}."
        )
    tail = ""
    stderr = run_dir / "stderr.log"
    if stderr.is_file():
        lines = [ln for ln in stderr.read_text(errors="replace").splitlines() if ln.strip()]
        lines = [ln for ln in lines if "pkg_resources" not in ln]
        tail = " | ".join(lines[-3:])
    return (
        f"Run {manifest.get('run_id')} ({manifest.get('label')!r}) failed with exit code "
        f"{manifest.get('exit_code')}. Last stderr lines: {tail or '(none)'}. "
        f"See {stderr} and {paths.find_log_file(run_dir / 'output') or run_dir / 'output'}."
    )
